apiVersion: v1
kind: Service
metadata:
  name: flask-lms-service
spec:
  selector:
    app: flask-lms
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008

